### ISSUE TITLE
KineticJS Project not supported anymore

### ISSUE THREAD

**Issue by steffimueller** [ericdrowell/KineticJS#1048]
It seem to me that the project is not supported anymore. Is there someone who will continue with this project?

**Comment by kangax** [comment]
I'd be interested to hear what Fabric is missing comparing to Kinetic (aside from support for seamless layering, which I always loved in Kinetic and which we're planning to add to Fabric in a near future).

**Comment by lavrton** [comment]
I will maintain KineticJS in a fork: https://github.com/lavrton/KineticJS
