### ISSUE TITLE
Do we need a fork?

### ISSUE THREAD

**Issue by lavrton** [ericdrowell/KineticJS#1052]
What is your thoughts guys? Do you need any support for KineticJS? Who is using KineticJS on what kind of projects?

**Comment by dave-ledsign** [comment]
I am using it as a critical part of a large project. Everything is working but I am nervous and am thinking about a rewrite of the critical part unless someone else is willing to pick up the ball.  I don't want to write any more code for kineticjs just in case it breaks with future browser versions.

**Comment by Arduinology** [comment]
Same boat as @dave-ledsign , we as a community should come together and support this. Just noticed today that their site is all but gone along with the documentation I relied on. Lets get this moving, how can I help?

**Comment by confile** [comment]
At least we should write a migration guide from KineticJS to PixiJS (http://www.pixijs.com/) Pixi uses WebGL Renderer with canvas fallback so it is much faster than Kinetic. What do you think of my idea?

**Comment by dave-ledsign** [comment]
I hadn't heard of PixiJS before @confile, so I can't comment on its quality, but a quick look suggests it will have the future support I am looking for. WebGL is an example of the advancement in browsers that I need to keep up with, and I am guessing kineticjs is already behind and probably can't catch up now.

**Comment by Arduinology** [comment]
I had not heard of PixiJS before either, can anyone comment on their experiences with this? What sort of work would it take to migrate to it?

**Comment by confile** [comment]
As you can see here: http://jsperf.com/js-anim/28 Pixijs performs most of the time much better than any other lib especially KineticJs. 

I suggest we open a github project which documents how to migrate to PixiJs. 

I created a project for this purpose here: https://github.com/confile/Kinetic2Pixi

Anyone how wants to join can contact me and I make you a collaborator on this project.

**Comment by bensquire** [comment]
I'm in a similar position to @dave-ledsign and @Arduinology , kineticJs plays a pivotal role in quite a complex system... It'll take many many hours to port the existing codebase over. I suspect we'll end up running the current version until it becomes completely unfit for purpose.

**Comment by lavrton** [comment]
Hello everyone. I decided to create a fork. As a contributor of current repo I think I can support KineticJS in a new fork. Repo and link will be ready in ~ one week.

**Comment by Pmleader** [comment]
Hello,
I'm very happy to read this!
Out project is run completely with KineticJS and rewriting it would take A LOT of time.
Much appreciated that you are taking initiative with continuing this great project!

**Comment by pmuston** [comment]
Excellent news. I spent a few days porting my code base to FabricJS, while discovering it was a poor fit for my use.
KineticJS's rich eventing model works better for my use case (an object graph editor), allowing parents and children within the visual hierarchy to have different handlers. The convenience of switching on and off layers is a wonderful trick to be able to employ.
While these techniques are reproducible in Fabric, but I found myself creating many more ancillary structures in my view model not related to my underlying model but to manage click targets when in a particular state and to compensate for Fabric's less rich event model. Eric did push forward the state of canvas frameworks to abstract this.
So I'm on board to continue with this great project.

**Comment by bensquire** [comment]
@lavrton Many thanks for picking up the mantle, If I can help somehow then just let me know.

**Comment by confile** [comment]
I think moving to PixiJs is much more promising because Pixi has a much greater support audience. Pixi also has WebGL support which makes you app super fast. 

So feel free to join our project to migrate a KineticJS app to PixiJS https://github.com/confile/Kinetic2Pixi

**Comment by lavrton** [comment]
@confile agree, PIXI (and Phaser) is really great. But it is different framework. In my opinion PIXI is best for games. But if you need a lot of "vector" graphics (such as text) you will have problems. This is my experience. I was thinking to move to Phaser in my main mind map application. In the app I need to draw a lot of nodes (with text) on canvas. It is possible to create custom graphics with PIXI. But for each graphics PIXI has separate canvas element in memory (You can not just draw text into webgl context, you have to convert text to image first, then you can display that image). So I had big memory leak. I was not able to find solution for this case.

**Comment by dave-ledsign** [comment]
Text in all kinds of fonts is the main thing I need. If Pixi is not great with text then that would be a deciding factor. I would like to help with Kinetic support if I can, at least until I know more about Pixi and/or other frameworks.  I will be running my own tests and would like to hear as much as possible about anyone else trying out other frameworks.

**Comment by pmuston** [comment]
@lavrton from your use case, our needs are somewhat similar - graphs (of the nodes and edges variety). WebGL based frameworks do not fit my use case at all. If the gamers are going to split off to PIXI then it would inform the future direction of Kinetic if we had a good idea of how the remaining Kinetic tribe are using it. I could be an active (i.e. useful) contributor if the project's abstraction was to further advance support for its role as a "direct manipulation interface" view controller, rather than to say adding WebGL support. For example, I am using Kinetic as a view controller (rendering, hit testing and subsequent modal interaction) hooked up to my underlying domain model which holds the ultimate truth. An example is dragging from one connector to another creating an edge between nodes in the model. Adding native support for a model (beyond the visual hierarchy, as in MVC) would be an excellent direction.

**Comment by bensquire** [comment]
We're developing a tool that allows users to proof read (markup) documents. Which means we have potentially hundreds of shapes grouped which can be manipulated (moved, resized, have events attached to them). We render vector shapes and text on the canvas and rely on the ability to stack the canvases as well. The whole thing is then wrapped up inside angularjs.

![screen shot 2015-01-09 at 14 51 17](https://cloud.githubusercontent.com/assets/600237/5681285/14eae0e2-980f-11e4-9fc6-bb242cb5dac2.png)

**Comment by dave-ledsign** [comment]
If I could add something to the wish list for future work in Kinetic, it would be more documentation.  Not just method names and parameters, but what methods actually do below the surface, what are best practises and why, and as many "Hello World + one feature at a time" examples and tests as possible.  I should stress that everything is working for me at the moment (thx Eric), it is the long-term for Kinetic and my project that I am thinking about.

**Comment by pmuston** [comment]
@bensquire very nice!

**Comment by confile** [comment]
Okay I suppose this is the new base repo https://github.com/lavrton/KineticJS

@lavrton How active will you be in development and bugfixing?

**Comment by Arduinology** [comment]
Right now I am at an impass, PixiJS has more performance (WebGL is just fast) but it does have issues with text. That being said I was able to get bitmap text in fairly easily once I found the tool for the job. The problem with PixiJS is that the text doesn't scale well, it is a linear scale for WebGL, this is supposedly going to be fixed but that was over a year ago. Text support just seems poor.

**Comment by dave-ledsign** [comment]
Bitmap text would not work for me. I need vectors so users can play in real-time with fill color, transparency and gradients, stroke width and color, shadows, etc. I am fine with converting fonts to vectors, but after that I need what Kinetic is currently doing for me.  Can anyone comment on PixiJS vectors, or is it 100% raster at this time?

**Comment by AlvinPLeung** [comment]
My corporate internal app requires similar capability for Anton's mind
map app.  Rich event model is a must.  Bitmap text with memory leak is a no
go.   I need the browser to stay healthy.  It does not make sense to force
my users to quit their browsers after using my web app.

Alvin

**Comment by lavrton** [comment]
Hello everyone. I made a fork. https://github.com/lavrton/KineticJS
The homepage is http://lavrton.github.io/KineticJS/

Also I made new version 5.1.9 with a lot of edits from last Eric's version. I will really happy if someone will help me with tutorials. See https://github.com/lavrton/KineticJS/tree/gh-pages#how-to-help.

I will still active in this repo's issues for a while.

**Comment by maxkorp** [comment]
Has anybody talked with Eric regarding posting a link in the readme?

**Comment by bensquire** [comment]
It did have a link up until 3 hours ago, but @ericdrowell seems to have removed it?

**Comment by lavrton** [comment]
Ops. I am really sad to see this... Waiting Eric's answer.
