### ISSUE TITLE
Transition of kinetic to https://github.com/konvajs

### ISSUE THREAD

**Issue by chris-rock** [ericdrowell/KineticJS#1055]
@ericdrowell thank you very much for your work so far. would it be possible to create a kineticjs org and hand over the code? This would allow all forkes to have one place to be.

**Comment by lavrton** [comment]
All forks may be merged in any repo (as in personal as in org).

But sure that is might be very good idea. Are there any other active forks?
PS: hmm. all good name already taken.

**Comment by lavrton** [comment]
As it is hart to evolve project under old name I decided to rename fork to `Konva` project. Fork is available in this organization: https://github.com/konvajs

**Comment by confile** [comment]
@lavrton  So kineticJS is now KonvaJS right?

**Comment by chris-rock** [comment]
great work @lavrton !
