### ISSUE TITLE
Rect should clip the cornerRadius when 2radius > height/width

### ISSUE THREAD

**Issue by jhr007** [ericdrowell/KineticJS#176]
Found this by accident.
goto 
http://www.html5canvastutorials.com/kineticjs/html5-canvas-kineticjs-rect-tutorial/

Use this instead of the Rect on the page. Notice the candy wrapper effect on the ends. 

```javascript
      var rect = new Kinetic.Rect({
        x: 75,
        y: 75,
        width: 400,
        height: 15,
        fill: 'dark gray',
        stroke: 'gray',
        strokeWidth: 2,
        cornerRadius: 20
      }
```

This could be a new Line endcap style :p 

Maybe something like this would work: (untested)
```javascript
config.cornerRadius= Math.min(config.cornerRadius, width/2, height/2);
```

**Comment by lavrton** [comment]
Resolved on fork. https://github.com/lavrton/KineticJS
