### ISSUE TITLE
No drop event?

### ISSUE THREAD

**Issue by ghost** [ericdrowell/KineticJS#201]
Hello,

Following the Kinetic tutorials I am able to intercept dragstart and dragend events (events triggered from the drag source), but not events related to a drag target, meaning 'drop' for example.

Here is a jsfiddle illustration (please check the console to see that drop and dragenter are not triggered):
http://jsfiddle.net/silently/B5x7z/

Am I doing it wrong or is this a bug?

Thanks,
Guillaume

**Comment by lavrton** [comment]
I made a demo with drop events support (drop, dragenter, dragleave, dragover). http://lavrton.github.io/KineticJS/Drag_and_Drop/Drop_Events.html
