### ISSUE TITLE
fillColor broken on new browsers

### ISSUE THREAD

**Issue by mitsuhiko** [ericdrowell/KineticJS#244]
Hi,

Kinetic.js currently uses `context.fill(context)` wrongly.  It should just be `context.fill()`.  Apparently current browsers did not cause an exception there but with Firefox 21 there is now a parameter it takes so it errors out with "TypeError: Value '[object CanvasRenderingContext2D]' is not a valid value for enumeration CanvasWindingRule. @ http://d3lp1msu2r81bx.cloudfront.net/kjs/js/lib/kinetic-v4.3.1.js:672"

Old:

```
    Kinetic.SceneCanvas.prototype = {
        _fillColor: function(shape) {
            var context = this.context, fill = shape.getFill();
            context.fillStyle = fill;
            context.fill(context);
        },
```

Fixed:

```
    Kinetic.SceneCanvas.prototype = {
        _fillColor: function(shape) {
            var context = this.context, fill = shape.getFill();
            context.fillStyle = fill;
            context.fill();
        },
```

**Comment by SainiMukesh** [comment]
Thanks mitsuhiko ,
it's working now, Really helpful.
