### ISSUE TITLE
IE10 touch events (MSPointerDown)

### ISSUE THREAD

**Issue by elainevdw** [ericdrowell/KineticJS#330]
I saw a closed issue asking for MS touch compatibility from a while back, but there wasn't an answer on if it got integrated or not. Basically, I'm trying to add an event listener to a Kinetic.Image. I'm told that the jQuery on('mousedown touchstart click') is working on a Surface tablet using the stylus or a mouse, but not touch. 

Here's my object:

```javascript
				var triangle = new Kinetic.Image({
					image: images[key],
					x: tri.x,
					y: tri.y,
					detectionType: "pixel"
				});
```

And here's what I'm playing around with currently. They already mentioned that .on('MSPointerDown') doesn't appear to be working, so I'm trying to attach it via .addEventListener. I figure if I can get addEventListener working with a normal click event, then the MSPointer event will *probably* be ok too? I don't have a Surface to test this on, which makes it harder.

Also, I'm using Kinetic v3.10.1, but the results are the same in 4.3.3, except in 4.3.3 the background doesn't load and I get an error on the .saveData() function farther down in the script.

```javascript
			
				triangle.on("mousedown touchstart click", activateTriangle);
				/*
				// I popped this in here to see if it would work, assuming that if it 
				// doesn't work for clicks, it won't work for pointer events.
				// This gives me the error, 
				// Uncaught TypeError: Object #<Object> has no method 'addEventListener' 
				triangle.addEventListener('click',function(){
					window.console && console.log('click event');
				});
				// And here's what I get for trying to iterate through it
				// Uncaught TypeError: Object #<Object> has no method 'addEventListener' wealth-management.php:305
				//	(anonymous function) wealth-management.php:305
				//	e.extend.each jquery-1.7.2.min.js:2
				//	e.fn.e.each jquery-1.7.2.min.js:2
				//	(anonymous function) wealth-management.php:304
				//	initStage wealth-management.php:318
				//	images.(anonymous function).onload
				$(triangle).each(function(){
					this.addEventListener('click',function(){
						window.console && console.log('hi');
					});
				});
				*/	
				/* Try for IE10 Touch */				
				if (window.navigator.msPointerEnabled) {
						window.console && console.log('msPointerEnabled');
						// click to correct info window
						triangle.on("MSPointerDown",activateTriangle); 
						//triangle.addEventListener("MSPointerDown", activateTriangle, false);
				}	
```

This is the actual page (using a temporary URL so the site doesn't live on in infamy in the Github archives, lol): http://www.urlgone.com/e8e1c2/

**Comment by lavrton** [comment]
Should be fixed.
