### ISSUE TITLE
Kinetic JS dragging a layer causes shapes on another layer to stop responding to drag (kinetic-v4.4.3.min.js)

### ISSUE THREAD

**Issue by EveryoneMustWin** [ericdrowell/KineticJS#404]
There is a problem in 4.4.3 where dragging a layer can interfere with shapes on another layer. The problem seems to be when setAttrs() is called on the other layer with {x:this.getX(), y:this.getY()} to try and keep the layers aligned.

Shapes on that layer which were draggable lose the ability to be dragged. It seems that creating a new draggable shape after that restores the desired behaviour.

This issue was not present in 4.3.3

Perhaps I'm not using it right?

http://jsfiddle.net/EveryoneMustWin/QRaxJ/

Thanks,
Oscar

**Comment by lavrton** [comment]
Fixed at fork. https://github.com/lavrton/KineticJS
