### ISSUE TITLE
Big Stage == Canvas Content is not shown on iPhone

### ISSUE THREAD

**Issue by solitud** [ericdrowell/KineticJS#430]
Hi,
if I set a stage with dimensions around 500 x 2620px Kineticjs does not render the canvas content on an iPhone.
It works in Apples iOS Simulator but not on the real device.

Kineticjs 4.4.3, iPhone 4S 6.1.3

**Comment by rajmohanperiyasamy** [comment]
Thank you so much guys...Bcz of you i have saved my time lot...I was facing the issue that canvas size gets doubled in ipad and i phones series when i was using kineticjs v4.4.1...later i updated from v4.4.1 to v4.4.3...Now everything works fine...
