### ISSUE TITLE
Kinetic.Group().on('click') bug 

### ISSUE THREAD

**Issue by dandyling** [ericdrowell/KineticJS#455]
I formed a Kinetic.Group, with a Kinetic.Rect and Kinetic.Text.  However, I noticed that there are some areas inside the group that is not detected by the 'click' event.  

I attach the jsfiddle as below, and an image showing a small red circle inside the drawn group, which shows where the event doesnt fire (please try to click multiple times in the area between 'S' and 't' character, you will spot it when the hit in the console log doesnt increase)

http://jsfiddle.net/GXWFY/5/

![click](https://f.cloud.github.com/assets/4457195/518019/1c37d636-bef2-11e2-989f-ab28bc138a29.png)

**Comment by hosamshahin** [comment]
@nicktgr15 :thumbsup:
