### ISSUE TITLE
strokeScaleEnabled set to false Line object failed to fire mouseover and mouseout event

### ISSUE THREAD

**Issue by AlvinPLeung** [ericdrowell/KineticJS#530]
When strokeScaleEnabled is set to false for Line object, the mouseover and mouseout event failed to fire.  May be the hit region's strokeScaleEnabled did not set to false.

I am using FireFox 22.0.  If mouse passes over the red line, the mouse pointer does not change.   If mouse passes over the green line, the mouser pointer changes from arrow to finger pointer.  Same issue exits for 4.4.3.

Example
<!DOCTYPE HTML>
<html>
  <head>
    <style>
      body {
        margin: 0px;
        padding: 0px;
      }
    </style>
  </head>
  <body>
    <div id="container"></div>
    <script src="http://d3lp1msu2r81bx.cloudfront.net/kjs/js/lib/kinetic-v4.5.4.min.js"></script>
    <script defer="defer">
      var scale = 0.1;

      var stage = new Kinetic.Stage({
        container: 'container',
        width: 578,
        height: 200
      });
      var layer = new Kinetic.Layer();

      var group = new Kinetic.Group({
         scale: [scale, scale],
      });

      var line1 = new Kinetic.Line({
        points: [73, 70, 340, 23, 450, 60, 500, 20],
        stroke: 'red',
        strokeScaleEnabled: false,
        strokeWidth: 5,
        lineCap: 'round',
        lineJoin: 'round'
      });

      line1.on('mouseover', function(evt) {
         document.body.style.cursor = "pointer";
      });

      line1.on('mouseout', function(evt) {
         document.body.style.cursor = "default";
      });
      group.add(line1);

      var line2 = new Kinetic.Line({
        points: [73, 70, 340, 23, 450, 60, 500, 20],
        stroke: 'green',
        strokeWidth: 5 / scale,
        lineCap: 'round',
        lineJoin: 'round'
      });

      line2.on('mouseover', function(evt) {
         document.body.style.cursor = "pointer";
      });

      line2.on('mouseout', function(evt) {
         document.body.style.cursor = "default";
      });

      group.add(line2);

      line1.move(100, 100);
      line2.move(100, 550);

      layer.add(group);
      stage.add(layer);

    </script>
  </body>
</html>

**Comment by lavrton** [comment]
Fixed at fork. https://github.com/lavrton/KineticJS
