### ISSUE TITLE
Mousemove event prevents click event firing

### ISSUE THREAD

**Issue by moea-chan** [ericdrowell/KineticJS#827]
Hi all,
I'm using KineticJs 4.7.2 with Chrome (33.0.1750.117 m) or Firefox (26).
My problem is when draggable is set on a layer, clicking on a node may fire mousemove event so onclick functions won't be called. So i've modified source code to check positions in mousemove function and if they're the same i fire click event. Has anyone else had info about this issue ? Is something planned in next versions ?
Thanks

**Comment by heke2929** [comment]
now `webkitMovementX` & `webkitMovementY` has been changed to public attr. I changed code.
20190220 i forgot to consider ie environment.
```js
_mousemove: function(evt) {
            if (!Kinetic.UA.mobile) {
                var webkitMovementFix = false, noWebkit = true
                if (typeof evt.webkitMovementX != 'undefined' || typeof evt.webkitMovementY != 'undefined') {
                    webkitMovementFix = !(evt.webkitMovementX === 0 && evt.webkitMovementY === 0)
                    noWebkit = false
                } else if (typeof evt.movementX != 'undefined' || typeof evt.movementY != 'undefined') {
                    webkitMovementFix = !(evt.movementX === 0 && evt.movementY === 0)
                    noWebkit = false
                }
                if (webkitMovementFix || noWebkit ) {
                    this._setPointerPosition(evt);

```
