### ISSUE TITLE
Brighten tutorial needs updating

### ISSUE THREAD

**Issue by kennardconsulting** [ericdrowell/KineticJS#833]
The tutorial here: http://www.html5canvastutorials.com/kineticjs/html5-canvas-kineticjs-brighten-or-darken-image-tutorial/

Says "The brightness property can be set to any integer between -255 and 255.  Negative values darken the image, and positive values brighten the image". However this results in extreme white or black images. If you look at the code, it is actually doing:

     <input id="slider" type="range" min="-1" max="1" step="0.05" value="0">

So it appears to be values between -1 and 1?

**Comment by lavrton** [comment]
fixed here: http://lavrton.github.io/KineticJS/Filters/Brighten.html
