### ISSUE TITLE
Tutorials link on the application site is broken.

### ISSUE THREAD

**Issue by sunrize531** [ericdrowell/KineticJS#980]
404 error here:
http://www.html5canvastutorials.com/kineticjs/html5-canvas-events-tutorials-introduction-with-kineticjs/

**Comment by lavrton** [comment]
All tutorials are repaired in new homepage. http://lavrton.github.io/KineticJS/Getting_Started.html

**Comment by pmuston** [comment]
New site looks excellent!!
